### ISSUE TITLE
document need for require/console

### ISSUE THREAD

**Issue by contra** [adobe-research/fondue#15]
the new vm module (contextify) does not provide anything to the sandbox so you need to specify require and console otherwise this won't work. should probably be in the docs somewhere

unrelated: why are require and console needed?

**Comment by alltom** [comment]
fondue only uses the vm module in its tests. [`console` and `require` get passed in every time](https://github.com/adobe-research/fondue/blob/master/test/helper/simulate.js#L48-L52). Did the API for passing objects into the VM change?

Both of the requirements come from [tracer.js](https://github.com/adobe-research/fondue/blob/master/tracer.js), which uses `console.log` to output debug information and to [determine when nodes in the call graph are log statements](https://github.com/adobe-research/fondue/blob/master/tracer.js#L1030-L1033), and uses `require` when Node.js mode is enabled to [get the "events" module](https://github.com/adobe-research/fondue/blob/master/tracer.js#L1185).

**Comment by contra** [comment]
@alltom Yeah, in 0.12 node switched the vm module to = contextify, nothing gets passed in by default - you need to specify all globals.

**Comment by alltom** [comment]
fondue does specify all the globals (the first link in my last comment). I guess I should upgrade my node at some point. :)

**Comment by contra** [comment]
@alltom I'm not understanding you. Code that is returned from fondue has a requirement on console.log and require being specified, which node DOES NOT do by default. I'm requesting that you add documentation so users know to specify this to prevent confusion. fondue doesn't run the code so I don't get what you mean by "fondue does specify all the globals"

**Comment by alltom** [comment]
Oh, I see what you're saying! You wanted to run fondue-generated code in vm, and were surprised to find that the code fondue generated required globals that your original code didn't. That makes sense. I'll update the documentation to say that. I can see why that would be very surprising!

(So that we can understand each other: I interpreted your comment to mean that fondue's tests were broken on the new node because fondue uses vm, and I was pointing out that even though it does use vm, it declares all the globals it needs: https://github.com/adobe-research/fondue/blob/master/test/helper/simulate.js#L48-L52)

**Comment by alltom** [comment]
Ah, and I bet you were referring to the examples at the top of the README, too... I'll fix those while I'm at it.
